### ISSUE TITLE
QtWebEngineWidgets ImportError

### ISSUE THREAD

**Issue by OaHolroyd** [moritzgloeckl/overleaf-sync#56]
OS: macOS 12.5.1
Python: 3.10

olbrowserlogin.py fails on `from PyQt5.QtWebEngineWidgets import *`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/olsync/olsync.py", line 26, in <module>
    import olsync.olbrowserlogin as olbrowserlogin
  File "/usr/local/lib/python3.10/site-packages/olsync/olbrowserlogin.py", line 15, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: dlopen(/usr/local/lib/python3.10/site-packages/PyQt5/QtWebEngineWidgets.abi3.so, 0x0002): Symbol not found: (_CGLGetCurrentContext)
  Referenced from: '/usr/local/lib/python3.10/site-packages/PyQt5/Qt5/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore'
  Expected in: '/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ols", line 5, in <module>
    from olsync.olsync import main
  File "/usr/local/lib/python3.10/site-packages/olsync/olsync.py", line 30, in <module>
    from . import olbrowserlogin
  File "/usr/local/lib/python3.10/site-packages/olsync/olbrowserlogin.py", line 15, in <module>
    from PyQt5.QtWebEngineWidgets import *
ImportError: dlopen(/usr/local/lib/python3.10/site-packages/PyQt5/QtWebEngineWidgets.abi3.so, 0x0002): Symbol not found: (_CGLGetCurrentContext)
  Referenced from: '/usr/local/lib/python3.10/site-packages/PyQt5/Qt5/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore'
  Expected in: '/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL'
```

**Comment by moritzgloeckl** [comment]
I guess it's the same issue as #47 - Are you on an M1/M2 Mac?

**Comment by moritzgloeckl** [comment]
I've just published ols version 1.2.0 could you please upgrade to this version and try again :)

**Comment by OaHolroyd** [comment]
I'm still getting the same issue:
```
Traceback (most recent call last):
  File "/usr/local/bin/ols", line 5, in <module>
    from olsync.olsync import main
  File "/usr/local/lib/python3.10/site-packages/olsync/olsync.py", line 27, in <module>
    import olsync.olbrowserlogin as olbrowserlogin
  File "/usr/local/lib/python3.10/site-packages/olsync/olbrowserlogin.py", line 14, in <module>
    from PySide6.QtWebEngineWidgets import *
ImportError: dlopen(/usr/local/lib/python3.10/site-packages/PySide6/QtWebEngineWidgets.abi3.so, 0x0002): Symbol not found: (_CGLGetCurrentContext)
  Referenced from: '/usr/local/lib/python3.10/site-packages/PySide6/Qt/lib/QtWebEngineCore.framework/Versions/A/QtWebEngineCore'
  Expected in: '/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL'
```

It's an intel Mac not an M1/M2

**Comment by OaHolroyd** [comment]
Found the issue - it was a problem my end with OpenGL. Verision 1.2.0 works fine now.
